openapi: 3.0.3
info:
  title: Report action in response to provided insights.
  version: 1.0.3
  description: This API provides the ability for IPP to report action taken in response to insights provided.
paths:
  /report/insights:
    post:
      summary: Bank Account outcomes
      description: |
        Report action taken in response to insights provided for the given Bank Account
      parameters:
        - in: header
          required: true
          name: User-Agent
          description: Any string id
          schema:
            type: string
            pattern: '.+'
            example: ipp
        - in: header
          required: false
          name: X-Tracking-Id
          description: Any string identifying the current session that will be inserted into audit trails.
          schema:
            type: string
            pattern: '.+'
            example: 6d5731a4-c927-4107-b81f-eb88288bf5c9
      requestBody:
        description: Description of outcome achieved based on insighs provided
        required: true
        content:
          'application/json':
            schema:
              type: object
              required:
                - correlationId
                - submitter
                - submission
                - outcome
              properties:
                correlationId:
                  type: string
                  format: uuid
                submitter:
                  type: string
                submission:
                  oneOf:
                    - $ref: "#/components/schemas/NINO_SUBMISSION"
                    - $ref: "#/components/schemas/BANK_ACCOUNT_SUBMISSION"
                outcome:
                  oneOf:
                    - $ref: "#/components/schemas/ACCEPTED"
                    - $ref: "#/components/schemas/INVESTIGATING"
                    - $ref: "#/components/schemas/REJECTED"
                    - $ref: "#/components/schemas/HOLD"
                    - $ref: "#/components/schemas/PAYMENT_ALLOCATED"
                    - $ref: "#/components/schemas/PAYMENT_NOT_ALLOCATED"
            examples: {
              {
                "correlationId": "33df37a4-a535-41fe-8032-7ab718b45526",
                "submitter": "ipp", //Unnecessary??
                "submission": {
                  "submissionType": "bank-account",
                  "submissionAttribute": {
                    "sortCode": "608580",
                    "accountNumber": "48835625"
                  }
                },
                "outcome": {
                  "outcomeType": "PAYMENT_ALLOCATION",
                  "decision": "PAYMENT_ALLOCATED",
                  "reasons": "account allocated to details", //freeform text - not parsed
                  "evidence": { //respond with either/or/and given relationships and new ones
                    "sa_utr": "0123456789",
                    "paye_ref": "ABC/A1234",
                    "full_name": "Jane Smith",
                    "user_id": "0123456789112345" //eg government gateway id of the end user - possibly an object type to hold type of used id
                  }
                }
              },
              {
                "correlationId": "33df37a4-a535-41fe-8032-7ab718b45526",
                "submitter": "ipp",
                "submission": {
                  "submissionType": "bank-account",
                  "submissionAttribute": {
                    "sortCode": "608581",
                    "accountNumber": "49835625"
                  }
                },
                "outcome": {
                  "outcomeType": "PAYMENT_ALLOCATION",
                  "decision": "PAYMENT_ALLOCATED",
                  "reasons": "account allocated to details",
                  "evidence": {
                    "ct_utr": "0123456789",
                    "agent_code": "ABC1234567ZX",
                    "user_id": "0123456789112345",
                    "vrn": "GB123456789"
                  }
                }
              }
            }
      responses:
        '200':
          description: |
            Indicates that the payload was successfully parsed.
        '400':
          description: |
            Indicates that the payload could not be parsed.
        '5XX':
          description: |
            An unexpected server error occurred when processing the request. These are usually temporary and consumers should try again.

components:
  schemas:
    NINO_SUBMISSION:
      type: object
      properties:
        submissionType:
          type: string
          enum:
            - "nino"
        submissionAttribute:
          type: object
          required:
            - nino
          properties:
            nino:
              type: string
              pattern: "[A-Za-z&&[^DFIQUdfiqu]][A-Za-z&&[^DFIQUOdfiquo]]\p{Digit}{6}[ABCDabcd]?"
    BANK_ACCOUNT_SUBMISSION:
      type: object
      properties:
        submissionType:
          type: string
          enum:
            - "bank-account"
        submissionAttribute:
          type: object
          required:
            - sortCode
            - accountNumber
          properties:
            sortCode:
              type: string
              minLength: 6
              maxLength: 6
              pattern: '([0-9]+){6}'
            accountNumber:
              type: string
              minLength: 8
              maxLength: 8
              pattern: '([0-9]+){8}'
    EVIDENCE:
      type: object
      description: |
        An object the contains attribute to value mappings that were helpful in working the case. 
        The attributes are restricted to ct_utr, paye_ref, sa_utr, user_id, vrn, person_full_name, agent_code.
    ACCEPTED:
      type: object
      required:
        - outcomeType
        - decision
        - reasons
      properties:
        outcomeType:
          type: string
          pattern: "Insights"
        decision:
          type: string
          pattern: "ACCEPTED"
        reasons:
          type: array
          items:
            type: string
            enum:
              - "LOW_RISK_SCORE"
              - "KNOWN_TRUSTED_CUSTOMER"
              - "OTHER_INFORMATION_NOT_PROVIDED_IN_RISK_OPINION"
              - "INVESTIGATION_CONCLUDES_NOT_FRAUD"
        evidence:
          $ref: "#/components/schemas/EVIDENCE"
    INVESTIGATING:
      type: object
      required:
        - outcomeType
        - decision
        - reasons
      properties:
        decision:
          type: string
          pattern: "INVESTIGATING"
        reasons:
          type: array
          items:
            type: string
            enum:
              - "HIGH_RISK_SCORE"
              - "KNOWN_UNTRUSTED_CUSTOMER"
              - "OTHER_INFORMATION_NOT_PROVIDED_IN_RISK_OPINION"
              - "RANDOM_AUDIT"
        evidence:
          $ref: "#/components/schemas/EVIDENCE"
    REJECTED:
      type: object
      required:
        - outcomeType
        - decision
        - reasons
      properties:
        outcomeType:
          type: string
          pattern: "Insights"
        decision:
          type: string
          pattern: "REJECTED"
        reasons:
          type: array
          items:
            type: string
            enum:
              - "HIGH_RISK_SCORE"
              - "KNOWN_UNTRUSTED_CUSTOMER"
              - "OTHER_INFORMATION_NOT_PROVIDED_IN_RISK_OPINION"
              - "INVESTIGATION_CONCLUDES_NOT_FRAUD"
              - "INVESTIGATION_CONCLUDES_NOT_ERROR"
              - "INCORRECT_INFORMATION"
              - "DUPLICATE_SUBMISSION"
              - "INCOMPLETE_SUBMISSION"
        evidence:
          $ref: "#/components/schemas/EVIDENCE"
    HOLD:
      type: object
      required:
        - outcomeType
        - decision
        - reasons
      properties:
        outcomeType:
          type: string
          pattern: "Insights"
        decision:
          type: string
          pattern: "HOLD"
        reasons:
          type: array
          items:
            type: string
            enum:
              - "AWAITING_FURTHER_INFORMATION"
        evidence:
          $ref: "#/components/schemas/EVIDENCE"
    PAYMENT_ALLOCATED:
      type: object
      required:
        - outcomeType
        - decision
        - reasons
      properties:
        outcomeType:
          type: string
          pattern: "PaymentAllocation"
        decision:
          type: string
          pattern: "PAYMENT_ALLOCATED"
        reasons:
          type: array
          items:
            type: string
            enum:
              - "INVESTIGATION_CONCLUDED"
              - "OTHER_INFORMATION_NOT_PROVIDED_IN_RISK_OPINION"
              - "FURTHER_DETAILS_OF_ACCOUNT_ALLOCATED_TO"
        evidence:
          $ref: "#/components/schemas/EVIDENCE"
    PAYMENT_NOT_ALLOCATED:
      type: object
      required:
        - outcomeType
        - decision
        - reasons
      properties:
        outcomeType:
          type: string
          pattern: "PaymentAllocation"
        decision:
          type: string
          pattern: "PAYMENT_NOT_ALLOCATED"
        reasons:
          type: array
          items:
            type: string
            enum:
              - "ASSOCIATED_TAX_ACCOUNT_NOT_FOUND"
              - "FURTHER_INVESTIGATION"
              - "OTHER_INFORMATION_NOT_PROVIDED_IN_RISK_OPINION"
              - "AWAITING_FURTHER_INFORMATION"
              - "INVESTIGATION_CONCLUDED"
        evidence:
          $ref: "#/components/schemas/EVIDENCE"
